steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/rts-game-379909/website:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rts-game-379909/website:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'website'
      - '--image=gcr.io/rts-game-379909/website:$COMMIT_SHA'
      - '--region=europe-north1'
      - '--platform=managed'
      - '--service-account=$$BALANCER_SERVICE_EMAIL'
      - '--ingress=internal-and-cloud-load-balancing'
    secretEnv: ['BALANCER_SERVICE_EMAIL']
images:
  - 'gcr.io/rts-game-379909/website:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/BALANCER_SERVICE_EMAIL/versions/latest
      env: 'BALANCER_SERVICE_EMAIL'
